{
    "2.0.0": {
        "info": {
            "author": "Fabian Joswig",
            "author_email": "fabian.joswig@ed.ac.uk",
            "bugtrack_url": null,
            "classifiers": [],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "pyerrors",
            "package_url": "https://pypi.org/project/pyerrors/",
            "platform": null,
            "project_url": "https://pypi.org/project/pyerrors/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/pyerrors/2.0.0/",
            "requires_dist": [
                "numpy (>=1.16)",
                "autograd (>=1.4)",
                "numdifftools",
                "matplotlib (>=3.3)",
                "scipy",
                "iminuit (>=2)",
                "h5py"
            ],
            "requires_python": ">=3.6.0",
            "summary": "Error analysis for lattice QCD",
            "version": "2.0.0",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 15461301,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "5651089258310a4ff4f155b44e9eb4b5",
                    "sha256": "2742e2f940f0aecdccc64a156e151bd01c020d59ef2564a379962232cabf31b4"
                },
                "downloads": -1,
                "filename": "pyerrors-2.0.0-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "5651089258310a4ff4f155b44e9eb4b5",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6.0",
                "size": 78130,
                "upload_time": "2022-05-19T09:05:02",
                "upload_time_iso_8601": "2022-05-19T09:05:02.417734Z",
                "url": "https://files.pythonhosted.org/packages/d8/b5/06b7494659426ecfdeaae16323d20b323dd8a29054df9b7cb07b6f1b1ebe/pyerrors-2.0.0-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            },
            {
                "comment_text": "",
                "digests": {
                    "md5": "3e521d4d31c6d54299969229539e61a7",
                    "sha256": "ae5842931f53f332f39e23ce1f33155c0709d442a1912eb3ef6611aae75a5f58"
                },
                "downloads": -1,
                "filename": "pyerrors-2.0.0.tar.gz",
                "has_sig": false,
                "md5_digest": "3e521d4d31c6d54299969229539e61a7",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": ">=3.6.0",
                "size": 1734270,
                "upload_time": "2022-05-19T09:05:07",
                "upload_time_iso_8601": "2022-05-19T09:05:07.246072Z",
                "url": "https://files.pythonhosted.org/packages/e2/1c/e2eef13bc931429eaea4683d77781177772cdb901db9a8b21f5c403b3076/pyerrors-2.0.0.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "2.1.0": {
        "info": {
            "author": "Fabian Joswig",
            "author_email": "fabian.joswig@ed.ac.uk",
            "bugtrack_url": null,
            "classifiers": [
                "Development Status :: 5 - Production/Stable",
                "Intended Audience :: Science/Research",
                "License :: OSI Approved :: MIT License",
                "Programming Language :: Python :: 3",
                "Programming Language :: Python :: 3.10",
                "Programming Language :: Python :: 3.7",
                "Programming Language :: Python :: 3.8",
                "Programming Language :: Python :: 3.9",
                "Topic :: Scientific/Engineering"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "https://github.com/fjosw/pyerrors",
            "keywords": "",
            "license": "MIT",
            "maintainer": "",
            "maintainer_email": "",
            "name": "pyerrors",
            "package_url": "https://pypi.org/project/pyerrors/",
            "platform": null,
            "project_url": "https://pypi.org/project/pyerrors/",
            "project_urls": {
                "Homepage": "https://github.com/fjosw/pyerrors"
            },
            "release_url": "https://pypi.org/project/pyerrors/2.1.0/",
            "requires_dist": [
                "numpy (>=1.16)",
                "autograd (>=1.4)",
                "numdifftools",
                "matplotlib (>=3.3)",
                "scipy",
                "iminuit (>=2)",
                "h5py",
                "lxml",
                "python-rapidjson"
            ],
            "requires_python": ">=3.6.0",
            "summary": "Error analysis for lattice QCD",
            "version": "2.1.0",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 15461301,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "de2da46e357b62e275d66a2a7a0e43c4",
                    "sha256": "6f8c8f5922656800a3cea9651e5e44e385cd31326ec0d61b6ffea8d056464df3"
                },
                "downloads": -1,
                "filename": "pyerrors-2.1.0-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "de2da46e357b62e275d66a2a7a0e43c4",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6.0",
                "size": 90461,
                "upload_time": "2022-05-31T11:09:47",
                "upload_time_iso_8601": "2022-05-31T11:09:47.363352Z",
                "url": "https://files.pythonhosted.org/packages/4a/68/f742742807beec2d34124132c1f55387f7d92e9a00f1583897511f0439f7/pyerrors-2.1.0-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            },
            {
                "comment_text": "",
                "digests": {
                    "md5": "8ba19937ef34a98e2f988502dc057cf6",
                    "sha256": "629652a3407cb0a81c4b349d06bc914d2ca345ca92a3d87a049268b2135a8530"
                },
                "downloads": -1,
                "filename": "pyerrors-2.1.0.tar.gz",
                "has_sig": false,
                "md5_digest": "8ba19937ef34a98e2f988502dc057cf6",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": ">=3.6.0",
                "size": 1739692,
                "upload_time": "2022-05-31T11:09:51",
                "upload_time_iso_8601": "2022-05-31T11:09:51.154465Z",
                "url": "https://files.pythonhosted.org/packages/b2/20/1ad7f4f9792245a90a8f2580bede9666b9d68eee6c8a949b751c8260b715/pyerrors-2.1.0.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "2.1.1": {
        "info": {
            "author": "Fabian Joswig",
            "author_email": "fabian.joswig@ed.ac.uk",
            "bugtrack_url": null,
            "classifiers": [
                "Development Status :: 5 - Production/Stable",
                "Intended Audience :: Science/Research",
                "License :: OSI Approved :: MIT License",
                "Programming Language :: Python :: 3",
                "Programming Language :: Python :: 3.10",
                "Programming Language :: Python :: 3.7",
                "Programming Language :: Python :: 3.8",
                "Programming Language :: Python :: 3.9",
                "Topic :: Scientific/Engineering"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "https://github.com/fjosw/pyerrors",
            "keywords": "",
            "license": "MIT",
            "maintainer": "",
            "maintainer_email": "",
            "name": "pyerrors",
            "package_url": "https://pypi.org/project/pyerrors/",
            "platform": null,
            "project_url": "https://pypi.org/project/pyerrors/",
            "project_urls": {
                "Bug Tracker": "https://github.com/fjosw/pyerrors/issues",
                "Documentation": "https://fjosw.github.io/pyerrors/pyerrors.html",
                "Homepage": "https://github.com/fjosw/pyerrors"
            },
            "release_url": "https://pypi.org/project/pyerrors/2.1.1/",
            "requires_dist": [
                "numpy (>=1.16)",
                "autograd (>=1.4)",
                "numdifftools",
                "matplotlib (>=3.3)",
                "scipy (>=1)",
                "iminuit (>=2)",
                "h5py",
                "lxml",
                "python-rapidjson"
            ],
            "requires_python": ">=3.6.0",
            "summary": "Error analysis for lattice QCD",
            "version": "2.1.1",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 15461301,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "be32235c24451ed3292f1a912da95126",
                    "sha256": "2068052d4a8edffce3f5c2a3bb9af6902600f02bf51f90f9a2e9506b53fce73d"
                },
                "downloads": -1,
                "filename": "pyerrors-2.1.1-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "be32235c24451ed3292f1a912da95126",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6.0",
                "size": 90513,
                "upload_time": "2022-06-06T14:59:47",
                "upload_time_iso_8601": "2022-06-06T14:59:47.203919Z",
                "url": "https://files.pythonhosted.org/packages/29/a9/03faa2f7406a2262fac3ab01eeac41a152646db98f1db8071086fb140d8e/pyerrors-2.1.1-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            },
            {
                "comment_text": "",
                "digests": {
                    "md5": "b01c72dbde03324d0893a71a6bcc3dc6",
                    "sha256": "3515981a7a1c603d37e17475ec541ef8b171f8ce5f47dc8e0f5c27116dff8cc7"
                },
                "downloads": -1,
                "filename": "pyerrors-2.1.1.tar.gz",
                "has_sig": false,
                "md5_digest": "b01c72dbde03324d0893a71a6bcc3dc6",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": ">=3.6.0",
                "size": 1740381,
                "upload_time": "2022-06-06T15:00:46",
                "upload_time_iso_8601": "2022-06-06T15:00:46.204995Z",
                "url": "https://files.pythonhosted.org/packages/97/31/c996f50d301cffdefe544b9ab2d3b1d5457d90e7c8baff73faa311bfcf8a/pyerrors-2.1.1.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "2.1.2": {
        "info": {
            "author": "Fabian Joswig",
            "author_email": "fabian.joswig@ed.ac.uk",
            "bugtrack_url": null,
            "classifiers": [
                "Development Status :: 5 - Production/Stable",
                "Intended Audience :: Science/Research",
                "License :: OSI Approved :: MIT License",
                "Programming Language :: Python :: 3",
                "Programming Language :: Python :: 3.10",
                "Programming Language :: Python :: 3.7",
                "Programming Language :: Python :: 3.8",
                "Programming Language :: Python :: 3.9",
                "Topic :: Scientific/Engineering :: Physics"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "https://github.com/fjosw/pyerrors",
            "keywords": "",
            "license": "MIT",
            "maintainer": "",
            "maintainer_email": "",
            "name": "pyerrors",
            "package_url": "https://pypi.org/project/pyerrors/",
            "platform": null,
            "project_url": "https://pypi.org/project/pyerrors/",
            "project_urls": {
                "Bug Tracker": "https://github.com/fjosw/pyerrors/issues",
                "Documentation": "https://fjosw.github.io/pyerrors/pyerrors.html",
                "Homepage": "https://github.com/fjosw/pyerrors"
            },
            "release_url": "https://pypi.org/project/pyerrors/2.1.2/",
            "requires_dist": [
                "numpy (>=1.16)",
                "autograd (>=1.4)",
                "numdifftools",
                "matplotlib (>=3.3)",
                "scipy (>=1)",
                "iminuit (>=2)",
                "h5py (>=3)",
                "lxml (>=4)",
                "python-rapidjson (>=1)"
            ],
            "requires_python": ">=3.6.0",
            "summary": "Error analysis for lattice QCD",
            "version": "2.1.2",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 15461301,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "d9399842c290ec586080c1807798f819",
                    "sha256": "148b3864fd1474067772cde035e73f5f4608203481d751c8dfdbc9ed7854c592"
                },
                "downloads": -1,
                "filename": "pyerrors-2.1.2-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "d9399842c290ec586080c1807798f819",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6.0",
                "size": 90555,
                "upload_time": "2022-06-10T09:27:07",
                "upload_time_iso_8601": "2022-06-10T09:27:07.545320Z",
                "url": "https://files.pythonhosted.org/packages/a9/35/8a380c3548b89d3245fa1cde2937fb08f36a3f38ad7b2c25d054856f84b6/pyerrors-2.1.2-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            },
            {
                "comment_text": "",
                "digests": {
                    "md5": "c0441ede0fb6b44f33695caf8a1a0356",
                    "sha256": "6a63b5fc56d61a8a334a3917a61a4ad2a2e7aaa6aa6e0b6c410ea175a81b0285"
                },
                "downloads": -1,
                "filename": "pyerrors-2.1.2.tar.gz",
                "has_sig": false,
                "md5_digest": "c0441ede0fb6b44f33695caf8a1a0356",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": ">=3.6.0",
                "size": 1741049,
                "upload_time": "2022-06-10T09:27:10",
                "upload_time_iso_8601": "2022-06-10T09:27:10.911662Z",
                "url": "https://files.pythonhosted.org/packages/a4/0c/adc1c07d476277843ea1981fda3819b150a76f2e25c76dbc214db93b8fe2/pyerrors-2.1.2.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "2.1.3": {
        "info": {
            "author": "Fabian Joswig",
            "author_email": "fabian.joswig@ed.ac.uk",
            "bugtrack_url": null,
            "classifiers": [
                "Development Status :: 5 - Production/Stable",
                "Intended Audience :: Science/Research",
                "License :: OSI Approved :: MIT License",
                "Programming Language :: Python :: 3",
                "Programming Language :: Python :: 3.10",
                "Programming Language :: Python :: 3.7",
                "Programming Language :: Python :: 3.8",
                "Programming Language :: Python :: 3.9",
                "Topic :: Scientific/Engineering :: Physics"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "https://github.com/fjosw/pyerrors",
            "keywords": "",
            "license": "MIT",
            "maintainer": "",
            "maintainer_email": "",
            "name": "pyerrors",
            "package_url": "https://pypi.org/project/pyerrors/",
            "platform": null,
            "project_url": "https://pypi.org/project/pyerrors/",
            "project_urls": {
                "Bug Tracker": "https://github.com/fjosw/pyerrors/issues",
                "Changelog": "https://github.com/fjosw/pyerrors/blob/master/CHANGELOG.md",
                "Documentation": "https://fjosw.github.io/pyerrors/pyerrors.html",
                "Homepage": "https://github.com/fjosw/pyerrors"
            },
            "release_url": "https://pypi.org/project/pyerrors/2.1.3/",
            "requires_dist": [
                "numpy (>=1.16)",
                "autograd (>=1.4)",
                "numdifftools",
                "matplotlib (>=3.3)",
                "scipy (>=1)",
                "iminuit (>=2)",
                "h5py (>=3)",
                "lxml (>=4)",
                "python-rapidjson (>=1)"
            ],
            "requires_python": ">=3.6.0",
            "summary": "Error analysis for lattice QCD",
            "version": "2.1.3",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 15461301,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "199af9c38992a82df654f73bccdf9239",
                    "sha256": "aaa7b80998961ea8b3c78afdaa4f5316cc236434952e0a367dc42caa0f1f84d1"
                },
                "downloads": -1,
                "filename": "pyerrors-2.1.3-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "199af9c38992a82df654f73bccdf9239",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6.0",
                "size": 90738,
                "upload_time": "2022-06-13T12:41:01",
                "upload_time_iso_8601": "2022-06-13T12:41:01.897524Z",
                "url": "https://files.pythonhosted.org/packages/df/5c/2241af23e17cab7cd75c475793531bfc0cc22ef2f75f2a964ead08b57567/pyerrors-2.1.3-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            },
            {
                "comment_text": "",
                "digests": {
                    "md5": "f4673a64b8cba86720b06a8466663f27",
                    "sha256": "22ee92f7a4e64b8841e743568a26218d0cf2c9a75dbb5c30e07442477c87b8bc"
                },
                "downloads": -1,
                "filename": "pyerrors-2.1.3.tar.gz",
                "has_sig": false,
                "md5_digest": "f4673a64b8cba86720b06a8466663f27",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": ">=3.6.0",
                "size": 1741416,
                "upload_time": "2022-06-13T12:41:06",
                "upload_time_iso_8601": "2022-06-13T12:41:06.270152Z",
                "url": "https://files.pythonhosted.org/packages/23/13/14f15b24e3c508aca396dd5c093579c154324353c0eedfa353c291acdcac/pyerrors-2.1.3.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "2.2.0": {
        "info": {
            "author": "Fabian Joswig",
            "author_email": "fabian.joswig@ed.ac.uk",
            "bugtrack_url": null,
            "classifiers": [
                "Development Status :: 5 - Production/Stable",
                "Intended Audience :: Science/Research",
                "License :: OSI Approved :: MIT License",
                "Programming Language :: Python :: 3",
                "Programming Language :: Python :: 3.10",
                "Programming Language :: Python :: 3.7",
                "Programming Language :: Python :: 3.8",
                "Programming Language :: Python :: 3.9",
                "Topic :: Scientific/Engineering :: Physics"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "https://github.com/fjosw/pyerrors",
            "keywords": "",
            "license": "MIT",
            "maintainer": "",
            "maintainer_email": "",
            "name": "pyerrors",
            "package_url": "https://pypi.org/project/pyerrors/",
            "platform": null,
            "project_url": "https://pypi.org/project/pyerrors/",
            "project_urls": {
                "Bug Tracker": "https://github.com/fjosw/pyerrors/issues",
                "Changelog": "https://github.com/fjosw/pyerrors/blob/master/CHANGELOG.md",
                "Documentation": "https://fjosw.github.io/pyerrors/pyerrors.html",
                "Homepage": "https://github.com/fjosw/pyerrors"
            },
            "release_url": "https://pypi.org/project/pyerrors/2.2.0/",
            "requires_dist": [
                "numpy (>=1.19)",
                "autograd (>=1.4)",
                "numdifftools",
                "matplotlib (>=3.3)",
                "scipy (>=1.5)",
                "iminuit (>=2)",
                "h5py (>=3)",
                "lxml (>=4)",
                "python-rapidjson (>=1)",
                "pandas (>=1.1)",
                "pysqlite3 (>=0.4)"
            ],
            "requires_python": ">=3.6.0",
            "summary": "Error analysis for lattice QCD",
            "version": "2.2.0",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 15461301,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "98e6eb6805b860ed9ec41093fedf8bde",
                    "sha256": "4b9fb655f2a7f3ea7f2f52353bfa274aa6a951ce8f0df3e3d60819de50e23091"
                },
                "downloads": -1,
                "filename": "pyerrors-2.2.0-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "98e6eb6805b860ed9ec41093fedf8bde",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6.0",
                "size": 93641,
                "upload_time": "2022-08-01T16:16:10",
                "upload_time_iso_8601": "2022-08-01T16:16:10.019892Z",
                "url": "https://files.pythonhosted.org/packages/fd/b7/24c4407595968657ba043cfcf617f4576533aa47a2cc484527b2341c022c/pyerrors-2.2.0-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            },
            {
                "comment_text": "",
                "digests": {
                    "md5": "8a78f8f4d57ba6ec00fe8fa556f3a280",
                    "sha256": "448c3dae878a9670deb86cc9e2e7300525ae01443b3c5dbb851f9a3a43cd3b34"
                },
                "downloads": -1,
                "filename": "pyerrors-2.2.0.tar.gz",
                "has_sig": false,
                "md5_digest": "8a78f8f4d57ba6ec00fe8fa556f3a280",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": ">=3.6.0",
                "size": 1745701,
                "upload_time": "2022-08-01T16:16:13",
                "upload_time_iso_8601": "2022-08-01T16:16:13.627472Z",
                "url": "https://files.pythonhosted.org/packages/d7/69/aec7520543e29ef980c426611a44066a5abf867eaaecdcb961c4bf4c0ae1/pyerrors-2.2.0.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "2.3.0": {
        "info": {
            "author": "Fabian Joswig",
            "author_email": "fabian.joswig@ed.ac.uk",
            "bugtrack_url": null,
            "classifiers": [
                "Development Status :: 5 - Production/Stable",
                "Intended Audience :: Science/Research",
                "License :: OSI Approved :: MIT License",
                "Programming Language :: Python :: 3",
                "Programming Language :: Python :: 3.10",
                "Programming Language :: Python :: 3.11",
                "Programming Language :: Python :: 3.7",
                "Programming Language :: Python :: 3.8",
                "Programming Language :: Python :: 3.9",
                "Topic :: Scientific/Engineering :: Physics"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "https://github.com/fjosw/pyerrors",
            "keywords": "",
            "license": "MIT",
            "maintainer": "",
            "maintainer_email": "",
            "name": "pyerrors",
            "package_url": "https://pypi.org/project/pyerrors/",
            "platform": null,
            "project_url": "https://pypi.org/project/pyerrors/",
            "project_urls": {
                "Bug Tracker": "https://github.com/fjosw/pyerrors/issues",
                "Changelog": "https://github.com/fjosw/pyerrors/blob/master/CHANGELOG.md",
                "Documentation": "https://fjosw.github.io/pyerrors/pyerrors.html",
                "Homepage": "https://github.com/fjosw/pyerrors"
            },
            "release_url": "https://pypi.org/project/pyerrors/2.3.0/",
            "requires_dist": [
                "numpy (>=1.19)",
                "autograd (>=1.5)",
                "numdifftools",
                "matplotlib (>=3.3)",
                "scipy (>=1.5)",
                "iminuit (>=2)",
                "h5py (>=3)",
                "lxml (>=4)",
                "python-rapidjson (>=1)",
                "pandas (>=1.1)",
                "pysqlite3 (>=0.4)"
            ],
            "requires_python": ">=3.6.0",
            "summary": "Statistical error analysis for Monte Carlo simulations",
            "version": "2.3.0",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 15461301,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "58de7773c598f207ae27cad18e143d80",
                    "sha256": "10d942c8e42a09533f29337e5431f88f6e1920fc525a5bea7dffb14f2e73a920"
                },
                "downloads": -1,
                "filename": "pyerrors-2.3.0-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "58de7773c598f207ae27cad18e143d80",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6.0",
                "size": 93855,
                "upload_time": "2022-10-13T11:16:29",
                "upload_time_iso_8601": "2022-10-13T11:16:29.639159Z",
                "url": "https://files.pythonhosted.org/packages/fb/62/b1ae628f7c255c807d49d96e97968abbbb08568c52458a70c36771fab371/pyerrors-2.3.0-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            },
            {
                "comment_text": "",
                "digests": {
                    "md5": "a8f2976f6c166727587e8678a3b4a8e9",
                    "sha256": "43e84fc1a8b8b0d43e1a05ab7c5909a0731fe9b6816446a5d94ba5fd234fb5af"
                },
                "downloads": -1,
                "filename": "pyerrors-2.3.0.tar.gz",
                "has_sig": false,
                "md5_digest": "a8f2976f6c166727587e8678a3b4a8e9",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": ">=3.6.0",
                "size": 1708720,
                "upload_time": "2022-10-13T11:16:33",
                "upload_time_iso_8601": "2022-10-13T11:16:33.966652Z",
                "url": "https://files.pythonhosted.org/packages/3c/c3/1ad420d9ade08014bdd2b4bf5cc4456ed12ff871fbe0e884c1bee973c7b5/pyerrors-2.3.0.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "2.3.1": {
        "info": {
            "author": "Fabian Joswig",
            "author_email": "fabian.joswig@ed.ac.uk",
            "bugtrack_url": null,
            "classifiers": [
                "Development Status :: 5 - Production/Stable",
                "Intended Audience :: Science/Research",
                "License :: OSI Approved :: MIT License",
                "Programming Language :: Python :: 3",
                "Programming Language :: Python :: 3.10",
                "Programming Language :: Python :: 3.11",
                "Programming Language :: Python :: 3.7",
                "Programming Language :: Python :: 3.8",
                "Programming Language :: Python :: 3.9",
                "Topic :: Scientific/Engineering :: Physics"
            ],
            "description": "[![flake8](https://github.com/fjosw/pyerrors/actions/workflows/flake8.yml/badge.svg)](https://github.com/fjosw/pyerrors/actions/workflows/flake8.yml) [![pytest](https://github.com/fjosw/pyerrors/actions/workflows/pytest.yml/badge.svg)](https://github.com/fjosw/pyerrors/actions/workflows/pytest.yml) [![](https://img.shields.io/badge/python-3.7+-blue.svg)](https://www.python.org/downloads/) [![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT) [![arXiv](https://img.shields.io/badge/arXiv-2209.14371-b31b1b.svg)](https://arxiv.org/abs/2209.14371)\n# pyerrors\n`pyerrors` is a python package for error computation and propagation of Markov chain Monte Carlo data.\n\n- **Documentation:** https://fjosw.github.io/pyerrors/pyerrors.html\n- **Examples:** https://github.com/fjosw/pyerrors/tree/develop/examples\n- **Contributing:** https://github.com/fjosw/pyerrors/blob/develop/CONTRIBUTING.md\n- **Bug reports:** https://github.com/fjosw/pyerrors/issues\n\n## Installation\nTo install the most recent release run\n```bash\npip install pyerrors     # Fresh install\npip install -U pyerrors  # Upgrade\n```\nto install the current `develop` version run\n```bash\npip install git+https://github.com/fjosw/pyerrors.git@develop\n```\n",
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "https://github.com/fjosw/pyerrors",
            "keywords": "",
            "license": "MIT",
            "maintainer": "",
            "maintainer_email": "",
            "name": "pyerrors",
            "package_url": "https://pypi.org/project/pyerrors/",
            "platform": null,
            "project_url": "https://pypi.org/project/pyerrors/",
            "project_urls": {
                "Bug Tracker": "https://github.com/fjosw/pyerrors/issues",
                "Changelog": "https://github.com/fjosw/pyerrors/blob/master/CHANGELOG.md",
                "Documentation": "https://fjosw.github.io/pyerrors/pyerrors.html",
                "Homepage": "https://github.com/fjosw/pyerrors"
            },
            "release_url": "https://pypi.org/project/pyerrors/2.3.1/",
            "requires_dist": [
                "numpy (>=1.19)",
                "autograd (>=1.5)",
                "numdifftools",
                "matplotlib (>=3.5)",
                "scipy (>=1.7)",
                "iminuit (>=2.17)",
                "h5py (>=3.7)",
                "lxml (>=4.9)",
                "python-rapidjson (>=1.9)",
                "pandas (>=1.1)"
            ],
            "requires_python": ">=3.7.0",
            "summary": "Statistical error analysis for Monte Carlo simulations",
            "version": "2.3.1",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 15461301,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "7ce0fc9c3a37179c54fee75f0c802611",
                    "sha256": "6e87c1738524df89d366f852804c5247e1737db6952c764d69cfd2f783cc2a1f"
                },
                "downloads": -1,
                "filename": "pyerrors-2.3.1-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "7ce0fc9c3a37179c54fee75f0c802611",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.7.0",
                "size": 94211,
                "upload_time": "2022-10-19T13:07:54",
                "upload_time_iso_8601": "2022-10-19T13:07:54.404823Z",
                "url": "https://files.pythonhosted.org/packages/ed/28/1577fef8a16b176b8dc1dd1713604c1328e3ba90da47957b3cd9e181aa24/pyerrors-2.3.1-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            },
            {
                "comment_text": "",
                "digests": {
                    "md5": "a254059a2a2c81c74a88b294b052fae3",
                    "sha256": "94ea39f3badef01cfcba2df887cba19cc0607ffebb0ff169b09fd6d0ceffdd66"
                },
                "downloads": -1,
                "filename": "pyerrors-2.3.1.tar.gz",
                "has_sig": false,
                "md5_digest": "a254059a2a2c81c74a88b294b052fae3",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": ">=3.7.0",
                "size": 1709528,
                "upload_time": "2022-10-19T13:07:57",
                "upload_time_iso_8601": "2022-10-19T13:07:57.992041Z",
                "url": "https://files.pythonhosted.org/packages/7b/1a/0da2d6c1dd1e7a91226a656c09929bc2e1501329c952f267bb3b1aa5582e/pyerrors-2.3.1.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    }
}