{
    "0.0.1": {
        "info": {
            "author": "FeeFort",
            "author_email": "bikov22022006@gmail.com",
            "bugtrack_url": null,
            "classifiers": [],
            "description_content_type": "",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "https://github.com/FeeFort/discord-error-generator",
            "keywords": "",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "DSErrorsGenerator",
            "package_url": "https://pypi.org/project/DSErrorsGenerator/",
            "platform": "",
            "project_url": "https://pypi.org/project/DSErrorsGenerator/",
            "project_urls": {
                "Homepage": "https://github.com/FeeFort/discord-error-generator"
            },
            "release_url": "https://pypi.org/project/DSErrorsGenerator/0.0.1/",
            "requires_dist": null,
            "requires_python": "",
            "summary": "Generate embeds with texts of your personal errors.",
            "version": "0.0.1",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 9858523,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "88b22153ef5118ec6a70ba27df9af6c2",
                    "sha256": "72dc494e12fa0e55a7b08d30555470a1e0dd5cc00eb35ee86f70ab70204e06fd"
                },
                "downloads": -1,
                "filename": "DSErrorsGenerator-0.0.1.tar.gz",
                "has_sig": false,
                "md5_digest": "88b22153ef5118ec6a70ba27df9af6c2",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": null,
                "size": 2285,
                "upload_time": "2021-03-22T20:16:28",
                "upload_time_iso_8601": "2021-03-22T20:16:28.949532Z",
                "url": "https://files.pythonhosted.org/packages/d5/e7/7a2cfd761c4523477a604984cb33dd983b5af9065e4e022e4df1be0722ed/DSErrorsGenerator-0.0.1.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.0.2": {
        "info": {
            "author": "FeeFort",
            "author_email": "bikov22022006@gmail.com",
            "bugtrack_url": null,
            "classifiers": [],
            "description_content_type": "",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "https://github.com/FeeFort/discord-error-generator",
            "keywords": "",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "DSErrorsGenerator",
            "package_url": "https://pypi.org/project/DSErrorsGenerator/",
            "platform": "",
            "project_url": "https://pypi.org/project/DSErrorsGenerator/",
            "project_urls": {
                "Homepage": "https://github.com/FeeFort/discord-error-generator"
            },
            "release_url": "https://pypi.org/project/DSErrorsGenerator/0.0.2/",
            "requires_dist": null,
            "requires_python": "",
            "summary": "Generate embeds with texts of your personal errors.",
            "version": "0.0.2",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 9858523,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "045453297b5a5f42d7bfcbb652fee726",
                    "sha256": "01c687440e65309665a0aad91cf4779a28de92a42769a3ae93f75d487f54a01b"
                },
                "downloads": -1,
                "filename": "DSErrorsGenerator-0.0.2.tar.gz",
                "has_sig": false,
                "md5_digest": "045453297b5a5f42d7bfcbb652fee726",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": null,
                "size": 2278,
                "upload_time": "2021-03-23T08:26:35",
                "upload_time_iso_8601": "2021-03-23T08:26:35.407988Z",
                "url": "https://files.pythonhosted.org/packages/81/3a/80250d7fd6d288e7f8a0cb00aff7a87796d57107c121d3de099d27cea052/DSErrorsGenerator-0.0.2.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.0.3": {
        "info": {
            "author": "FeeFort",
            "author_email": "bikov22022006@gmail.com",
            "bugtrack_url": null,
            "classifiers": [],
            "description_content_type": "",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "https://github.com/FeeFort/discord-error-generator",
            "keywords": "",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "DSErrorsGenerator",
            "package_url": "https://pypi.org/project/DSErrorsGenerator/",
            "platform": "",
            "project_url": "https://pypi.org/project/DSErrorsGenerator/",
            "project_urls": {
                "Homepage": "https://github.com/FeeFort/discord-error-generator"
            },
            "release_url": "https://pypi.org/project/DSErrorsGenerator/0.0.3/",
            "requires_dist": null,
            "requires_python": "",
            "summary": "Generate embeds with texts of your personal errors.",
            "version": "0.0.3",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 9858523,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "65c0d0294552572153e02d12741f2c42",
                    "sha256": "35c350b27c3a395541eabd0c89ecc581178994a2bde3c5f270849ee8d013d2b1"
                },
                "downloads": -1,
                "filename": "DSErrorsGenerator-0.0.3.tar.gz",
                "has_sig": false,
                "md5_digest": "65c0d0294552572153e02d12741f2c42",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": null,
                "size": 2326,
                "upload_time": "2021-03-23T19:58:10",
                "upload_time_iso_8601": "2021-03-23T19:58:10.430736Z",
                "url": "https://files.pythonhosted.org/packages/cf/0b/f5f23668e0f991fadcf4509fe8c74596a2a69129f9c351cdc7031dc791f7/DSErrorsGenerator-0.0.3.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.0.4": {
        "info": {
            "author": "FeeFort",
            "author_email": "bikov22022006@gmail.com",
            "bugtrack_url": null,
            "classifiers": [],
            "description": "Documentation: https://bit.ly/3sa1aL6",
            "description_content_type": "",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "https://github.com/FeeFort/discord-error-generator",
            "keywords": "",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "DSErrorsGenerator",
            "package_url": "https://pypi.org/project/DSErrorsGenerator/",
            "platform": "",
            "project_url": "https://pypi.org/project/DSErrorsGenerator/",
            "project_urls": {
                "Homepage": "https://github.com/FeeFort/discord-error-generator"
            },
            "release_url": "https://pypi.org/project/DSErrorsGenerator/0.0.4/",
            "requires_dist": null,
            "requires_python": "",
            "summary": "Generate embeds with texts of your personal errors.",
            "version": "0.0.4",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 9858523,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "d7df63890e4f4bd21c57aecdc88a7ce9",
                    "sha256": "2d66826470d897d2c1ede07d3d204c580234e2f1d72504454bade76cf7b3e3ce"
                },
                "downloads": -1,
                "filename": "DSErrorsGenerator-0.0.4.tar.gz",
                "has_sig": false,
                "md5_digest": "d7df63890e4f4bd21c57aecdc88a7ce9",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": null,
                "size": 2315,
                "upload_time": "2021-03-23T20:17:44",
                "upload_time_iso_8601": "2021-03-23T20:17:44.704014Z",
                "url": "https://files.pythonhosted.org/packages/6e/dc/c81e12d48e4f434c1ccf00d1e2a63527a9e2a686f2b4c379801250b52291/DSErrorsGenerator-0.0.4.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    }
}